Test flask
Chera1/ru-study-python pull request #1
Opened 2023-04-26 08:01 UTC by Chera1

2023-05-03 07:16 UTC, aleksandr-semenov-dbp requested changes

2023-05-03 07:16 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +            elif data.get('name', None):
`elif 'name' in data:` ?

2023-05-03 07:16 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +            else:
после return можно не писать else

2023-05-03 07:16 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +        def delete(username):
Тогда уж и здесь надо обработать 404

2023-05-03 08:43 UTC, Chera1 reviewed
Changed flask excercise

2023-05-17 07:15 UTC, aleksandr-semenov-dbp requested changes

2023-05-17 07:15 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +            elif 'name' in data:
а что вернется если это условие не выполнено? Я все-таки настаиваю, что после return не надо писать else (в данном случае заменить elif на if и будет более заметно что в некоторых случаях функция не возвращает вообще ничего)

2023-05-17 07:15 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +            else:
Почему resolved?

2023-05-17 07:24 UTC, Chera1 commented on flask_exercises/flask_excercises.py
> +            else:
Ошибся. Исправил

2023-05-22 07:45 UTC, aleksandr-semenov-dbp approved these changes

2023-05-22 07:51 UTC, merged