Test maps
Chera1/ru-study-python pull request #3
Opened 2023-04-26 08:02 UTC by Chera1

2023-05-03 07:11 UTC, aleksandr-semenov-dbp requested changes

2023-05-03 07:11 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +        if len(movie['country'].split(',')) > 1:
Подсчет числа запятых split-ом неэффективен

2023-05-03 07:11 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +            if movie['rating_kinopoisk'] and float(movie['rating_kinopoisk']) > 0:
В таком случае надо не вкладывать if а объединять условия

2023-05-03 09:45 UTC, Chera1 commented on maps/maps.py
> +        if len(movie['country'].split(',')) > 1:
Первое, что пришло на ум это проверка с помощью 1)метода списка count; 2) оператора принадлежности in. Замерил среднюю скорость подсчета среди 10 тестов одного и второго варианта, получилось, что in в среднем на 2-3 секунды на данный массив значения быстрее (~6 секунд и ~4 секунды соответственно).  Предыдущий алгоритм срабатывал вдвое дольше оператора принадлежности.

2023-05-17 07:08 UTC, aleksandr-semenov-dbp approved these changes

2023-05-17 07:59 UTC, merged