Test lists
Chera1/ru-study-python pull request #4
Opened 2023-04-26 08:02 UTC by Chera1

2023-05-03 07:06 UTC, aleksandr-semenov-dbp requested changes

2023-05-03 07:06 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +            max_element = max(input_list)
В этом задании по условию нельзя использовать max()

2023-05-03 07:06 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +            return mid
Когда в if..else есть ветка с одной строчкой return имеет смысл поставить ее первой (в if), тогда else вообще писать не надо, экономим отступ, повышаем читаемость.

Что произойдет если элемента нет в списке? Надо обработать ситуацию

2023-05-03 10:27 UTC, Chera1 commented on lists/lists.py
> +            return mid
Проверка на отсутствие элемента в списке находится на 25 строке.

2023-05-17 07:02 UTC, aleksandr-semenov-dbp approved these changes

2023-05-17 07:02 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +            max_element = sorted(input_list)[-1]
неэффективное получение максимума

2023-05-22 07:51 UTC, merged